name: Build iOS App

on:
  push:
    branches:
      - main  # Sadece "main" branch'e push yapıldığında çalışır

jobs:
  build-ios:
    runs-on: macos-latest  # macOS gereklidir

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'

      - name: Install Dependencies
        run: flutter pub get

      - name: Setup Xcode
        run: sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer

      - name: Build iOS App
        run: |
          flutter build ipa --release \
            --export-options-plist=ios/Runner/ExportOptions.plist

      - name: Upload iOS Build as Artifact
        uses: actions/upload-artifact@v4  # <- Sürüm "v4" olacak!
        with:
          name: ios-app
          path: build/ios/ipa/*.ipa
