name: Build iOS App

on:
  push:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest  # macOS kullanmak zorunlu
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29'  # Güncel Flutter versiyonunu kullan

      - name: Install Dependencies
        run: flutter pub get

      - name: Setup Xcode
        run: sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer

      - name: Build iOS App
        run: |
          flutter build ipa --release \
            --export-options-plist=ios/Runner/ExportOptions.plist

      - name: Upload iOS Build
        uses: actions/upload-artifact@v3
        with:
          name: ios-app
          path: build/ios/ipa/*.ipa
