name: Build iOS IPA

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: '>=3.7.0 <4.0.0'

    - name: Install dependencies
      run: dart pub get

    - name: Build
      run: flutter build ipa