name: Build iOS IPA

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.5'  # Kullandığınız Flutter sürümünü belirtin

      - name: Get Flutter packages
        run: flutter pub get

      # iOS release build (codesigning olmadan)
      - name: Build iOS Release (No Codesign)
        run: flutter build ios --release --no-codesign

      # IPA oluşturmak için (Flutter 3.7+ ile kullanılabilir)
      - name: Build IPA
        run: flutter build ipa --export-method ad-hoc --no-codesign

      # IPA dosyasını arşivlemek veya yüklemek için ek adımlar ekleyebilirsiniz.
